In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
import pandas as pd
from sklearn.model_selection import train_test_split  

In [2]:
f = open("/Users/shreyassrinivasan/Desktop/SF_Project_Alias/merge_final.csv")
df = pd.read_csv(f)

In [3]:
df = df.dropna()

In [4]:
for i in df.columns:
    print(i)

Unnamed: 0
Unnamed: 0_x
Year
Quarter
Month
DayofMonth
FlightDate
OriginAirportID
Origin
DestAirportID
Dest
CRSDepTime
DepTime
DepDelayMinutes
DepDel15
CRSArrTime
ArrTime
ArrDelayMinutes
ArrDel15
ArrFlightDate
ArrAbsTime
DepAbsTime
Unnamed: 0_y
windspeedKmph_x
winddirDegree_x
weatherCode_x
precipMM_x
visibility_x
pressure_x
cloudcover_x
DewPointF_x
WindGustKmph_x
tempF_x
WindChillF_x
humidity_x
date_x
time_x
airport_x
Unnamed: 0.1
windspeedKmph_y
winddirDegree_y
weatherCode_y
precipMM_y
visibility_y
pressure_y
cloudcover_y
DewPointF_y
WindGustKmph_y
tempF_y
WindChillF_y
humidity_y
date_y
time_y
airport_y


In [5]:
x = df.drop(['Unnamed: 0','Unnamed: 0_x','DepDel15','ArrTime','ArrDelayMinutes','ArrDel15',
            'ArrFlightDate','ArrAbsTime','DepAbsTime','Unnamed: 0_y','date_x','time_x','airport_x','Unnamed: 0.1',
            'date_y','time_y','airport_y','FlightDate','OriginAirportID','DestAirportID','DepTime'],axis=1)

In [6]:
x.transpose()

0       1       2       3       4       5       6        \
Year               2016    2016    2016    2016    2016    2016    2016   
Quarter               4       4       4       4       4       4       4   
Month                12      12      12      12      12      12      12   
DayofMonth            1       1       1       1       1       1       1   
Origin              MCO     MIA     LAX     SFO     DEN     DEN     DFW   
Dest                ORD     ORD     ORD     ORD     ORD     ORD     ORD   
CRSDepTime         1400    1355    1100    1045    1235    1240    1420   
DepDelayMinutes       4       0       0      80       0       0       0   
CRSArrTime         1601    1617    1652    1647    1600    1606    1645   
windspeedKmph_x      15      14       5       5       7       7      17   
winddirDegree_x     237     138     111      35     248     248     174   
weatherCode_x       119     353     113     113     122     122     113   
precipMM_x            0     0.8       0       0       0       0       0   
visibility_x         10      10      10      10      10      10      10   
pressure_x         1015    1016    1016    1020    1016    1016    1019   
cloudcover_x         61      74       7       4      89      89       0   
DewPointF_x          67      73      51      51      10      10      28   
WindGustKmph_x       18      20       6       7       8       8      21   
tempF_x              84      82      66      58      38      38      60   
WindChillF_x         82      81      64      57      33      33      58   
humidity_x           62      79      62      84      33      33      33   
windspeedKmph_y      23      23      23      23      23      23      23   
winddirDegree_y     256     256     256     256     256     256     256   
weatherCode_y       119     119     119     119     119     119     119   
precipMM_y            0       0       0       0       0       0       0   
visibility_y         10      10      10      10      10      10      10   
pressure_y         1012    1012    1012    1012    1012    1012    1012   
cloudcover_y         97      97      97      97      97      97      97   
DewPointF_y          34      34      34      34      34      34      34   
WindGustKmph_y       30      30      30      30      30      30      30   
tempF_y              41      41      41      41      41      41      41   
WindChillF_y         33      33      33      33      33      33      33   
humidity_y           79      79      79      79      79      79      79   

                7       8       9        ... 1877184 1877185 1877186 1877187  \
Year               2016    2016    2016  ...    2017    2017    2017    2017   
Quarter               4       4       4  ...       1       1       1       1   
Month                12      12      12  ...       2       2       2       2   
DayofMonth            1       1       1  ...      13      18      25       4   
Origin              PHX     ATL     EWR  ...     JFK     JFK     JFK     DFW   
Dest                ORD     ORD     ORD  ...     LAX     LAX     LAX     PHX   
CRSDepTime         1141    1510    1500  ...    2250    2245    2245    2326   
DepDelayMinutes       2       4      24  ...      30       0       0       0   
CRSArrTime         1610    1617    1629  ...     200     158     158      55   
windspeedKmph_x       5      15      23  ...      28      16      25      15   
winddirDegree_x     121     292     256  ...     309     222     243     171   
weatherCode_x       116     113     113  ...     113     116     176     122   
precipMM_x            0       0       0  ...       0       0     3.1       0   
visibility_x         10      10      10  ...      10      10      10      10   
pressure_x         1016    1018    1005  ...    1014    1005    1000    1019   
cloudcover_x         58       0       1  ...       7      75      54     100   
DewPointF_x          22      39      41  ...      23      40      45      43   
WindGustKmph_x        7  

In [7]:
flightOrigin = {'DFW':1,'EWR':2,'IAH':3,'JFK':4,'LAS':5,'LAX':6,'MCO':7,'MIA':8,'ORD':9,'PHX':10,'SEA':11,'SFO':12,'ATL':13,'CLT':14,'DEN':15} 

In [8]:
arr1 = [df['Origin'].apply(lambda x: flightOrigin.get(x))]

In [9]:
arr2 = [df['Dest'].apply(lambda x: flightOrigin.get(x))]

In [10]:
x['newOrigin'] = arr1[0]

In [11]:
x['newDest'] = arr2[0]

In [12]:
x = x.drop(['Origin','Dest'],axis=1)

In [13]:
x.transpose()

0        1        2        3        4        5        \
Year              2016.0   2016.0   2016.0   2016.0   2016.0   2016.0   
Quarter              4.0      4.0      4.0      4.0      4.0      4.0   
Month               12.0     12.0     12.0     12.0     12.0     12.0   
DayofMonth           1.0      1.0      1.0      1.0      1.0      1.0   
CRSDepTime        1400.0   1355.0   1100.0   1045.0   1235.0   1240.0   
DepDelayMinutes      4.0      0.0      0.0     80.0      0.0      0.0   
CRSArrTime        1601.0   1617.0   1652.0   1647.0   1600.0   1606.0   
windspeedKmph_x     15.0     14.0      5.0      5.0      7.0      7.0   
winddirDegree_x    237.0    138.0    111.0     35.0    248.0    248.0   
weatherCode_x      119.0    353.0    113.0    113.0    122.0    122.0   
precipMM_x           0.0      0.8      0.0      0.0      0.0      0.0   
visibility_x        10.0     10.0     10.0     10.0     10.0     10.0   
pressure_x        1015.0   1016.0   1016.0   1020.0   1016.0   1016.0   
cloudcover_x        61.0     74.0      7.0      4.0     89.0     89.0   
DewPointF_x         67.0     73.0     51.0     51.0     10.0     10.0   
WindGustKmph_x      18.0     20.0      6.0      7.0      8.0      8.0   
tempF_x             84.0     82.0     66.0     58.0     38.0     38.0   
WindChillF_x        82.0     81.0     64.0     57.0     33.0     33.0   
humidity_x          62.0     79.0     62.0     84.0     33.0     33.0   
windspeedKmph_y     23.0     23.0     23.0     23.0     23.0     23.0   
winddirDegree_y    256.0    256.0    256.0    256.0    256.0    256.0   
weatherCode_y      119.0    119.0    119.0    119.0    119.0    119.0   
precipMM_y           0.0      0.0      0.0      0.0      0.0      0.0   
visibility_y        10.0     10.0     10.0     10.0     10.0     10.0   
pressure_y        1012.0   1012.0   1012.0   1012.0   1012.0   1012.0   
cloudcover_y        97.0     97.0     97.0     97.0     97.0     97.0   
DewPointF_y         34.0     34.0     34.0     34.0     34.0     34.0   
WindGustKmph_y      30.0     30.0     30.0     30.0     30.0     30.0   
tempF_y             41.0     41.0     41.0     41.0     41.0     41.0   
WindChillF_y        33.0     33.0     33.0     33.0     33.0     33.0   
humidity_y          79.0     79.0     79.0     79.0     79.0     79.0   
newOrigin            7.0      8.0      6.0     12.0     15.0     15.0   
newDest              9.0      9.0      9.0      9.0      9.0      9.0   

                 6        7        8        9        ...  1877184  1877185  \
Year              2016.0   2016.0   2016.0   2016.0  ...   2017.0   2017.0   
Quarter              4.0      4.0      4.0      4.0  ...      1.0      1.0   
Month               12.0     12.0     12.0     12.0  ...      2.0      2.0   
DayofMonth           1.0      1.0      1.0      1.0  ...     13.0     18.0   
CRSDepTime        1420.0   1141.0   1510.0   1500.0  ...   2250.0   2245.0   
DepDelayMinutes      0.0      2.0      4.0     24.0  ...     30.0      0.0   
CRSArrTime        1645.0   1610.0   1617.0   1629.0  ...    200.0    158.0   
windspeedKmph_x     17.0      5.0     15.0     23.0  ...     28.0     16.0   
winddirDegree_x    174.0    121.0    292.0    256.0  ...    309.0    222.0   
weatherCode_x      113.0    116.0    113.0    113.0  ...    113.0    116.0   
precipMM_x           0.0      0.0      0.0      0.0  ...      0.0      0.0   
visibility_x        10.0     10.0     10.0     10.0  ...     10.0     10.0   
pressure_x        1019.0   1016.0   1018.0   1005.0  ...   1014.0   1005.0   
cloudcover_x         0.0     58.0      0.0      1.0  ...      7.0     75.0   
DewPointF_x         28.0     22.0     39.0     41.0  ...     23.0     40.0   
WindGustKmph_x      21.0      7.0     18.0     32.0  ...     38.0     34.0   
tempF_x             60.0     51.0     57.0     52.0  ...     30.0     47.0   
WindChillF_x        58.0     50.0     53.0     46.0  ...     18.0     44.0   
humidity_x          33.0     34.0     54.0     70.0 

In [14]:
y = df['ArrDel15']

In [15]:
x.shape

(1851334, 33)

In [16]:
y.shape

(1851334,)

In [17]:
np.any(np.isnan(x))

False

In [18]:
np.all(np.isfinite(x))

True

In [19]:
# Splitting data into training and testing data

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 40)

In [20]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()

In [21]:
logReg.fit(x_train,y_train)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [22]:
# Accuracy

score = logReg.score(x_test,y_test)
print(score)

0.9156797662227528


In [23]:
pred = logReg.predict(x_test)

In [24]:
# Confusion matrix

cm = confusion_matrix(y_test,pred)

In [25]:
cm

array([[285647,   6658],
       [ 24563,  53399]])

In [26]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.98      0.95    292305
     Class 1       0.89      0.68      0.77     77962

    accuracy                           0.92    370267
   macro avg       0.90      0.83      0.86    370267
weighted avg       0.91      0.92      0.91    370267



In [27]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier

decTree = DecisionTreeClassifier()

In [28]:
decTree.fit(x_train, y_train)

DecisionTreeClassifier()

In [29]:
pred1 = decTree.predict(x_test)

In [30]:
cm1 = confusion_matrix(y_test,pred1)

In [31]:
cm1

array([[266976,  25329],
       [ 22728,  55234]])

In [32]:
# Accuracy

score1 = decTree.score(x_test,y_test)
print(score1)

0.8702098755762734


In [33]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred1,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.91      0.92    292305
     Class 1       0.69      0.71      0.70     77962

    accuracy                           0.87    370267
   macro avg       0.80      0.81      0.81    370267
weighted avg       0.87      0.87      0.87    370267



In [34]:
# Extra Tree Classifier

from sklearn.tree import ExtraTreeClassifier

extTree = ExtraTreeClassifier()

In [35]:
extTree.fit(x_train,y_train)

ExtraTreeClassifier()

In [36]:
pred2 = extTree.predict(x_test)

In [37]:
cm2 = confusion_matrix(y_test,pred2)

In [38]:
cm2

array([[258706,  33599],
       [ 33417,  44545]])

In [39]:
# Accuracy

score2 = extTree.score(x_test,y_test)
print(score2)

0.8190062846540469


In [40]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred2,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.89      0.89      0.89    292305
     Class 1       0.57      0.57      0.57     77962

    accuracy                           0.82    370267
   macro avg       0.73      0.73      0.73    370267
weighted avg       0.82      0.82      0.82    370267



In [41]:
# XG Boost

from xgboost import XGBClassifier

xgb = XGBClassifier()

In [42]:
xgb.fit(x_train, y_train)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[15:37:16] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [43]:
pred3 = xgb.predict(x_test)

In [44]:
cm3 = confusion_matrix(y_test,pred3)

In [45]:
cm3

array([[286229,   6076],
       [ 23514,  54448]])

In [46]:
# Accuracy

score3 = xgb.score(x_test,y_test)
print(score3)

0.9200846956385528


In [47]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred3,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.98      0.95    292305
     Class 1       0.90      0.70      0.79     77962

    accuracy                           0.92    370267
   macro avg       0.91      0.84      0.87    370267
weighted avg       0.92      0.92      0.92    370267



In [48]:
# Random Forest

from sklearn.ensemble import RandomForestClassifier  

ranFor = RandomForestClassifier(n_estimators= 30, criterion="entropy")  

In [49]:
ranFor.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [50]:
pred4 = ranFor.predict(x_test)

In [51]:
cm4 = confusion_matrix(y_test,pred4)

In [52]:
cm4

array([[285259,   7046],
       [ 23436,  54526]])

In [53]:
# Accuracy

score4 = ranFor.score(x_test,y_test)
print(score4)

0.9176756232664537


In [54]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred4,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.98      0.95    292305
     Class 1       0.89      0.70      0.78     77962

    accuracy                           0.92    370267
   macro avg       0.90      0.84      0.87    370267
weighted avg       0.92      0.92      0.91    370267

