In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
import pandas as pd
from sklearn.model_selection import train_test_split  
from imblearn.over_sampling import RandomOverSampler,SMOTE
import collections

In [2]:
f = open("/Users/shreyassrinivasan/Desktop/SF_Project_Alias/merge_final.csv")
df = pd.read_csv(f)

In [3]:
df = df.dropna()

In [4]:
x = df.drop(['Unnamed: 0','Unnamed: 0_x','DepDel15','ArrTime','ArrDelayMinutes','ArrDel15',
            'ArrFlightDate','ArrAbsTime','DepAbsTime','Unnamed: 0_y','date_x','time_x','airport_x','Unnamed: 0.1',
            'date_y','time_y','airport_y','FlightDate','OriginAirportID','DestAirportID','DepTime'],axis=1)

In [5]:
flightOrigin = {'DFW':1,'EWR':2,'IAH':3,'JFK':4,'LAS':5,'LAX':6,'MCO':7,'MIA':8,'ORD':9,'PHX':10,'SEA':11,'SFO':12,'ATL':13,'CLT':14,'DEN':15} 

In [6]:
arr1 = [df['Origin'].apply(lambda x: flightOrigin.get(x))]

In [7]:
arr2 = [df['Dest'].apply(lambda x: flightOrigin.get(x))]

In [8]:
x['newOrigin'] = arr1[0]

In [9]:
x['newDest'] = arr2[0]

In [10]:
x = x.drop(['Origin','Dest'],axis=1)

In [11]:
x.transpose()

0        1        2        3        4        5        \
Year              2016.0   2016.0   2016.0   2016.0   2016.0   2016.0   
Quarter              4.0      4.0      4.0      4.0      4.0      4.0   
Month               12.0     12.0     12.0     12.0     12.0     12.0   
DayofMonth           1.0      1.0      1.0      1.0      1.0      1.0   
CRSDepTime        1400.0   1355.0   1100.0   1045.0   1235.0   1240.0   
DepDelayMinutes      4.0      0.0      0.0     80.0      0.0      0.0   
CRSArrTime        1601.0   1617.0   1652.0   1647.0   1600.0   1606.0   
windspeedKmph_x     15.0     14.0      5.0      5.0      7.0      7.0   
winddirDegree_x    237.0    138.0    111.0     35.0    248.0    248.0   
weatherCode_x      119.0    353.0    113.0    113.0    122.0    122.0   
precipMM_x           0.0      0.8      0.0      0.0      0.0      0.0   
visibility_x        10.0     10.0     10.0     10.0     10.0     10.0   
pressure_x        1015.0   1016.0   1016.0   1020.0   1016.0   1016.0   
cloudcover_x        61.0     74.0      7.0      4.0     89.0     89.0   
DewPointF_x         67.0     73.0     51.0     51.0     10.0     10.0   
WindGustKmph_x      18.0     20.0      6.0      7.0      8.0      8.0   
tempF_x             84.0     82.0     66.0     58.0     38.0     38.0   
WindChillF_x        82.0     81.0     64.0     57.0     33.0     33.0   
humidity_x          62.0     79.0     62.0     84.0     33.0     33.0   
windspeedKmph_y     23.0     23.0     23.0     23.0     23.0     23.0   
winddirDegree_y    256.0    256.0    256.0    256.0    256.0    256.0   
weatherCode_y      119.0    119.0    119.0    119.0    119.0    119.0   
precipMM_y           0.0      0.0      0.0      0.0      0.0      0.0   
visibility_y        10.0     10.0     10.0     10.0     10.0     10.0   
pressure_y        1012.0   1012.0   1012.0   1012.0   1012.0   1012.0   
cloudcover_y        97.0     97.0     97.0     97.0     97.0     97.0   
DewPointF_y         34.0     34.0     34.0     34.0     34.0     34.0   
WindGustKmph_y      30.0     30.0     30.0     30.0     30.0     30.0   
tempF_y             41.0     41.0     41.0     41.0     41.0     41.0   
WindChillF_y        33.0     33.0     33.0     33.0     33.0     33.0   
humidity_y          79.0     79.0     79.0     79.0     79.0     79.0   
newOrigin            7.0      8.0      6.0     12.0     15.0     15.0   
newDest              9.0      9.0      9.0      9.0      9.0      9.0   

                 6        7        8        9        ...  1877184  1877185  \
Year              2016.0   2016.0   2016.0   2016.0  ...   2017.0   2017.0   
Quarter              4.0      4.0      4.0      4.0  ...      1.0      1.0   
Month               12.0     12.0     12.0     12.0  ...      2.0      2.0   
DayofMonth           1.0      1.0      1.0      1.0  ...     13.0     18.0   
CRSDepTime        1420.0   1141.0   1510.0   1500.0  ...   2250.0   2245.0   
DepDelayMinutes      0.0      2.0      4.0     24.0  ...     30.0      0.0   
CRSArrTime        1645.0   1610.0   1617.0   1629.0  ...    200.0    158.0   
windspeedKmph_x     17.0      5.0     15.0     23.0  ...     28.0     16.0   
winddirDegree_x    174.0    121.0    292.0    256.0  ...    309.0    222.0   
weatherCode_x      113.0    116.0    113.0    113.0  ...    113.0    116.0   
precipMM_x           0.0      0.0      0.0      0.0  ...      0.0      0.0   
visibility_x        10.0     10.0     10.0     10.0  ...     10.0     10.0   
pressure_x        1019.0   1016.0   1018.0   1005.0  ...   1014.0   1005.0   
cloudcover_x         0.0     58.0      0.0      1.0  ...      7.0     75.0   
DewPointF_x         28.0     22.0     39.0     41.0  ...     23.0     40.0   
WindGustKmph_x      21.0      7.0     18.0     32.0  ...     38.0     34.0   
tempF_x             60.0     51.0     57.0     52.0  ...     30.0     47.0   
WindChillF_x        58.0     50.0     53.0     46.0  ...     18.0     44.0   
humidity_x          33.0     34.0     54.0     70.0 

In [12]:
y = df['ArrDel15']

In [13]:
x.shape

(1851334, 33)

In [14]:
y.shape

(1851334,)

In [15]:
np.any(np.isnan(x))

False

In [16]:
np.all(np.isfinite(x))

True

In [17]:
# Splitting data into training and testing data

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 40)

In [18]:
ros = RandomOverSampler(random_state = 42)
x_resampled1,y_resampled1 = ros.fit_resample(x_train,y_train)

In [52]:
smote = SMOTE()
x_resampled2,y_resampled2 = smote.fit_resample(x_train,y_train)

In [53]:
print("Oversampling using RandomOverSampler: "+ str(collections.Counter(y_resampled1)))
print("Oversampling using SMOTE: "+ str(collections.Counter(y_resampled2)))

Oversampling using RandomOverSampler: Counter({0.0: 1170990, 1.0: 1170990})
Oversampling using SMOTE: Counter({0.0: 1170990, 1.0: 1170990})


In [ ]:
"""

"""

In [ ]:
# SMOTE

In [50]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()

In [54]:
logReg.fit(x_resampled2,y_resampled2)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [55]:
# Accuracy

score = logReg.score(x_test,y_test)
print(score)

0.8956617792025754


In [56]:
pred = logReg.predict(x_test)

In [57]:
# Confusion matrix

cm = confusion_matrix(y_test,pred)

In [58]:
cm

array([[270692,  21613],
       [ 17020,  60942]])

In [59]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.94      0.93      0.93    292305
     Class 1       0.74      0.78      0.76     77962

    accuracy                           0.90    370267
   macro avg       0.84      0.85      0.85    370267
weighted avg       0.90      0.90      0.90    370267



In [60]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier

decTree = DecisionTreeClassifier()

In [61]:
decTree.fit(x_resampled2, y_resampled2)

DecisionTreeClassifier()

In [62]:
pred1 = decTree.predict(x_test)

In [63]:
cm1 = confusion_matrix(y_test,pred1)
cm1

array([[265282,  27023],
       [ 22602,  55360]])

In [64]:
# Accuracy

score1 = decTree.score(x_test,y_test)
print(score1)

0.8659750936486373


In [65]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred1,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.91      0.91    292305
     Class 1       0.67      0.71      0.69     77962

    accuracy                           0.87    370267
   macro avg       0.80      0.81      0.80    370267
weighted avg       0.87      0.87      0.87    370267



In [66]:
# Extra Tree Classifier

from sklearn.tree import ExtraTreeClassifier

extTree = ExtraTreeClassifier()

In [67]:
extTree.fit(x_resampled2,y_resampled2)

ExtraTreeClassifier()

In [68]:
pred2 = extTree.predict(x_test)

In [69]:
cm2 = confusion_matrix(y_test,pred2)

In [70]:
cm2

array([[244224,  48081],
       [ 29622,  48340]])

In [71]:
# Accuracy

score2 = extTree.score(x_test,y_test)
print(score2)

0.7901433290031248


In [72]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred2,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.89      0.84      0.86    292305
     Class 1       0.50      0.62      0.55     77962

    accuracy                           0.79    370267
   macro avg       0.70      0.73      0.71    370267
weighted avg       0.81      0.79      0.80    370267



In [79]:
# XG Boost

from xgboost import XGBClassifier

xgb = XGBClassifier()

In [80]:
xgb.fit(x_resampled2,y_resampled2)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[11:49:41] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [81]:
pred3 = xgb.predict(x_test)

In [82]:
cm3 = confusion_matrix(y_test,pred3)

In [83]:
cm3

array([[284385,   7920],
       [ 22662,  55300]])

In [84]:
# Accuracy

score3 = xgb.score(x_test,y_test)
print(score3)

0.9174055478884157


In [85]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred3,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.93      0.97      0.95    292305
     Class 1       0.87      0.71      0.78     77962

    accuracy                           0.92    370267
   macro avg       0.90      0.84      0.87    370267
weighted avg       0.92      0.92      0.91    370267



In [73]:
# Random Forest

from sklearn.ensemble import RandomForestClassifier  

ranFor = RandomForestClassifier(n_estimators= 30, criterion="entropy")  

In [74]:
ranFor.fit(x_resampled2,y_resampled2)

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [75]:
pred4 = ranFor.predict(x_test)

In [76]:
cm4 = confusion_matrix(y_test,pred4)

cm4

array([[277077,  15228],
       [ 18242,  59720]])

In [77]:
# Accuracy

score4 = ranFor.score(x_test,y_test)
print(score4)

0.909605770970678


In [78]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred4,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.94      0.95      0.94    292305
     Class 1       0.80      0.77      0.78     77962

    accuracy                           0.91    370267
   macro avg       0.87      0.86      0.86    370267
weighted avg       0.91      0.91      0.91    370267



In [ ]:
# Using Random Over Sampler

In [19]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()

In [20]:
logReg.fit(x_resampled1,y_resampled1)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [21]:
# Accuracy

score = logReg.score(x_test,y_test)
print(score)

0.8960668922696324


In [23]:
pred = logReg.predict(x_test)

In [24]:
# Confusion matrix

cm = confusion_matrix(y_test,pred)

cm

array([[270945,  21360],
       [ 17123,  60839]])

In [25]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.94      0.93      0.93    292305
     Class 1       0.74      0.78      0.76     77962

    accuracy                           0.90    370267
   macro avg       0.84      0.85      0.85    370267
weighted avg       0.90      0.90      0.90    370267



In [26]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier

decTree = DecisionTreeClassifier()

In [27]:
decTree.fit(x_resampled1, y_resampled1)

DecisionTreeClassifier()

In [28]:
pred1 = decTree.predict(x_test)

In [29]:
cm1 = confusion_matrix(y_test,pred1)
cm1

array([[268245,  24060],
       [ 23338,  54624]])

In [30]:
# Accuracy

score1 = decTree.score(x_test,y_test)
print(score1)

0.8719896723175439


In [31]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred1,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.92      0.92    292305
     Class 1       0.69      0.70      0.70     77962

    accuracy                           0.87    370267
   macro avg       0.81      0.81      0.81    370267
weighted avg       0.87      0.87      0.87    370267



In [32]:
# Extra Tree Classifier

from sklearn.tree import ExtraTreeClassifier

extTree = ExtraTreeClassifier()

In [33]:
extTree.fit(x_resampled1,y_resampled1)

ExtraTreeClassifier()

In [34]:
pred2 = extTree.predict(x_test)

In [35]:
cm2 = confusion_matrix(y_test,pred2)
cm2

array([[261591,  30714],
       [ 32348,  45614]])

In [36]:
# Accuracy

score2 = extTree.score(x_test,y_test)
print(score2)

0.8296850651016698


In [37]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred2,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.89      0.89      0.89    292305
     Class 1       0.60      0.59      0.59     77962

    accuracy                           0.83    370267
   macro avg       0.74      0.74      0.74    370267
weighted avg       0.83      0.83      0.83    370267



In [38]:
# XG Boost

from xgboost import XGBClassifier
xgb = XGBClassifier()

In [39]:
xgb.fit(x_resampled1,y_resampled1)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[10:10:39] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [40]:
pred3 = xgb.predict(x_test)

In [41]:
cm3 = confusion_matrix(y_test,pred3)
cm3

array([[269265,  23040],
       [ 15101,  62861]])

In [42]:
# Accuracy

score3 = xgb.score(x_test,y_test)
print(score3)

0.8969905500625225


In [43]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred3,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.95      0.92      0.93    292305
     Class 1       0.73      0.81      0.77     77962

    accuracy                           0.90    370267
   macro avg       0.84      0.86      0.85    370267
weighted avg       0.90      0.90      0.90    370267



In [44]:
# Random Forest

from sklearn.ensemble import RandomForestClassifier  

ranFor = RandomForestClassifier(n_estimators= 30, criterion="entropy")  

In [45]:
ranFor.fit(x_resampled1,y_resampled1)

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [46]:
pred4 = ranFor.predict(x_test)

In [47]:
cm4 = confusion_matrix(y_test,pred4)
cm4

array([[280912,  11393],
       [ 20351,  57611]])

In [48]:
# Accuracy

score4 = ranFor.score(x_test,y_test)
print(score4)

0.914267271995614


In [49]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred4,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.93      0.96      0.95    292305
     Class 1       0.83      0.74      0.78     77962

    accuracy                           0.91    370267
   macro avg       0.88      0.85      0.87    370267
weighted avg       0.91      0.91      0.91    370267

