In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

In [2]:
f = open("/Users/shreyassrinivasan/Desktop/SF_Project/merge_final.csv")
df = pd.read_csv(f)
df

Unnamed: 0  Unnamed: 0_x  Year  Quarter  Month  DayofMonth  \
0                 0           529  2016        4     12           1   
1                 1        243575  2016        4     12           1   
2                 2         33638  2016        4     12           1   
3                 3         64939  2016        4     12           1   
4                 4         63972  2016        4     12           1   
...             ...           ...   ...      ...    ...         ...   
1877189     1877189       5587516  2017        1      2          25   
1877190     1877190       5604625  2017        1      2          19   
1877191     1877191       5631975  2017        1      2          18   
1877192     1877192       5660860  2017        1      2          25   
1877193     1877193       5663924  2017        1      2          26   

         FlightDate  OriginAirportID Origin  DestAirportID  ... pressure_y  \
0        2016-12-01            11298    DFW          12892  ...       1014   
1        2016-12-01            11298    DFW          12892  ...       1014   
2        2016-12-01            13930    ORD          12892  ...       1014   
3        2016-12-01            13303    MIA          12892  ...       1014   
4        2016-12-01            14771    SFO          12892  ...       1014   
...             ...              ...    ...            ...  ...        ...   
1877189  2017-02-25            11298    DFW          14107  ...       1014   
1877190  2017-02-19            12889    LAS          12892  ...       1010   
1877191  2017-02-18            12889    LAS          12892  ...       1000   
1877192  2017-02-25            12889    LAS          12892  ...       1020   
1877193  2017-02-26            12889    LAS          12892  ...       1016   

         cloudcover_y  DewPointF_y  WindGustKmph_y  tempF_y  WindChillF_y  \
0                   0           59              10       69            67   
1                   0           59              10       69            67   
2                   0           59              10       69            67   
3                   0           59              10       69            67   
4                   0           59              10       69            67   
...               ...          ...             ...      ...           ...   
1877189           100           32              10       57            57   
1877190           100           51               5       52            52   
1877191           100           50              32       53            49   
1877192            36           45              13       47            45   
1877193            90           47               5       52            52   

         humidity_y      date_y  time_y airport_y  
0                73  2016-12-01    1700       LAX  
1                73  2016-12-01    1700       LAX  
2                73  2016-12-01    1700       LAX  
3                73  2016-12-01    1700       LAX  
4                73  2016-12-01    1700       LAX  
...             ...         ...     ...       ...  
1877189          39  2017-02-26       0       PHX  
1877190          95  2017-02-19     600       LAX  
1877191          92  2017-02-18     600       LAX  
1877192          93  2017-02-25     600       LAX  
1877193          85  2017-02-26     600       LAX  

[1877194 rows x 54 columns]

In [3]:
for i in df.columns:
    print(i)

Unnamed: 0
Unnamed: 0_x
Year
Quarter
Month
DayofMonth
FlightDate
OriginAirportID
Origin
DestAirportID
Dest
CRSDepTime
DepTime
DepDelayMinutes
DepDel15
CRSArrTime
ArrTime
ArrDelayMinutes
ArrDel15
ArrFlightDate
ArrAbsTime
DepAbsTime
Unnamed: 0_y
windspeedKmph_x
winddirDegree_x
weatherCode_x
precipMM_x
visibility_x
pressure_x
cloudcover_x
DewPointF_x
WindGustKmph_x
tempF_x
WindChillF_x
humidity_x
date_x
time_x
airport_x
Unnamed: 0.1
windspeedKmph_y
winddirDegree_y
weatherCode_y
precipMM_y
visibility_y
pressure_y
cloudcover_y
DewPointF_y
WindGustKmph_y
tempF_y
WindChillF_y
humidity_y
date_y
time_y
airport_y


In [6]:
"""
Unnamed: 0
Unnamed: 0_x
DepTime
DepDelayMinutes
DepDel15
ArrTime
FlightDate
ArrDelayMinutes
ArrDel15
ArrFlightDate
ArrAbsTime
DepAbsTime
Unnamed: 0_y
date_x
time_x
airport_x
Unnamed: 0.1
date_y
time_y
airport_y
"""

x = df.drop(['Unnamed: 0','Unnamed: 0_x','DepTime','DepDelayMinutes','DepDel15','ArrTime','ArrDelayMinutes','ArrDel15',
            'ArrFlightDate','ArrAbsTime','DepAbsTime','Unnamed: 0_y','date_x','time_x','airport_x','Unnamed: 0.1',
            'date_y','time_y','airport_y','FlightDate','Origin','Dest'],axis=1)
x

Year  Quarter  Month  DayofMonth  OriginAirportID  DestAirportID  \
0        2016        4     12           1            11298          12892   
1        2016        4     12           1            11298          12892   
2        2016        4     12           1            13930          12892   
3        2016        4     12           1            13303          12892   
4        2016        4     12           1            14771          12892   
...       ...      ...    ...         ...              ...            ...   
1877189  2017        1      2          25            11298          14107   
1877190  2017        1      2          19            12889          12892   
1877191  2017        1      2          18            12889          12892   
1877192  2017        1      2          25            12889          12892   
1877193  2017        1      2          26            12889          12892   

         CRSDepTime  CRSArrTime  windspeedKmph_x  winddirDegree_x  ...  \
0              1630        1758               19              169  ...   
1              1600        1741               19              169  ...   
2              1505        1747               24              257  ...   
3              1415        1719               15              140  ...   
4              1550        1725               10              117  ...   
...             ...         ...              ...              ...  ...   
1877189        2328          58                6              122  ...   
1877190         550         655                3              201  ...   
1877191         550         655               18              138  ...   
1877192         550         655                3               97  ...   
1877193         550         655                5              335  ...   

         weatherCode_y  precipMM_y  visibility_y  pressure_y  cloudcover_y  \
0                  113         0.0            10        1014             0   
1                  113         0.0            10        1014             0   
2                  113         0.0            10        1014             0   
3                  113         0.0            10        1014             0   
4                  113         0.0            10        1014             0   
...                ...         ...           ...         ...           ...   
1877189            122         0.0            10        1014           100   
1877190            143         0.0             2        1010           100   
1877191            353         2.1             8        1000           100   
1877192            116         0.0            10        1020            36   
1877193            263         0.5             3        1016            90   

         DewPointF_y  WindGustKmph_y  tempF_y  WindChillF_y  humidity_y  
0                 59              10       69            67          73  
1                 59              10       69            67          73  
2                 59              10       69            67          73  
3                 59              10       69            67          73  
4                 59              10       69            67          73  
...              ...             ...      ...           ...         ...  
1877189           32              10       57            57          39  
1877190           51               5       52            52          95  
1877191           50              32       53            49          92  
1877192           45              13       47            45          93  
1877193           47               5       52            52          85  

[1877194 rows x 32 columns]

In [7]:
x.transpose()

0        1        2        3        4        5        \
Year              2016.0   2016.0   2016.0   2016.0   2016.0   2016.0   
Quarter              4.0      4.0      4.0      4.0      4.0      4.0   
Month               12.0     12.0     12.0     12.0     12.0     12.0   
DayofMonth           1.0      1.0      1.0      1.0      1.0      1.0   
OriginAirportID  11298.0  11298.0  13930.0  13303.0  14771.0  11292.0   
DestAirportID    12892.0  12892.0  12892.0  12892.0  12892.0  12892.0   
CRSDepTime        1630.0   1600.0   1505.0   1415.0   1550.0   1625.0   
CRSArrTime        1758.0   1741.0   1747.0   1719.0   1725.0   1755.0   
windspeedKmph_x     19.0     19.0     24.0     15.0     10.0      3.0   
winddirDegree_x    169.0    169.0    257.0    140.0    117.0    111.0   
weatherCode_x      113.0    113.0    119.0    116.0    113.0    113.0   
precipMM_x           0.0      0.0      0.0      0.8      0.0      0.0   
visibility_x        10.0     10.0     10.0     10.0     10.0     10.0   
pressure_x        1018.0   1018.0   1012.0   1015.0   1020.0   1014.0   
cloudcover_x         0.0      0.0     96.0     70.0      0.0      1.0   
DewPointF_x         27.0     27.0     34.0     73.0     45.0      9.0   
WindGustKmph_x      23.0     23.0     31.0     21.0     12.0      6.0   
tempF_x             63.0     63.0     42.0     83.0     62.0     38.0   
WindChillF_x        61.0     61.0     33.0     81.0     60.0     35.0   
humidity_x          27.0     27.0     77.0     78.0     59.0     32.0   
windspeedKmph_y      8.0      8.0      8.0      8.0      8.0      8.0   
winddirDegree_y    261.0    261.0    261.0    261.0    261.0    261.0   
weatherCode_y      113.0    113.0    113.0    113.0    113.0    113.0   
precipMM_y           0.0      0.0      0.0      0.0      0.0      0.0   
visibility_y        10.0     10.0     10.0     10.0     10.0     10.0   
pressure_y        1014.0   1014.0   1014.0   1014.0   1014.0   1014.0   
cloudcover_y         0.0      0.0      0.0      0.0      0.0      0.0   
DewPointF_y         59.0     59.0     59.0     59.0     59.0     59.0   
WindGustKmph_y      10.0     10.0     10.0     10.0     10.0     10.0   
tempF_y             69.0     69.0     69.0     69.0     69.0     69.0   
WindChillF_y        67.0     67.0     67.0     67.0     67.0     67.0   
humidity_y          73.0     73.0     73.0     73.0     73.0     73.0   

                 6        7        8        9        ...  1877184  1877185  \
Year              2016.0   2016.0   2016.0   2016.0  ...   2017.0   2017.0   
Quarter              4.0      4.0      4.0      4.0  ...      1.0      1.0   
Month               12.0     12.0     12.0     12.0  ...      2.0      2.0   
DayofMonth           1.0      1.0      1.0      1.0  ...     12.0     11.0   
OriginAirportID  14107.0  11057.0  11292.0  10397.0  ...  14771.0  14771.0   
DestAirportID    12892.0  12892.0  12892.0  12892.0  ...  14747.0  14747.0   
CRSDepTime        1725.0   1450.0   1555.0   1501.0  ...    550.0    550.0   
CRSArrTime        1745.0   1726.0   1730.0   1710.0  ...    755.0    755.0   
windspeedKmph_x      5.0     14.0      1.0     15.0  ...      3.0     13.0   
winddirDegree_x    278.0    275.0    132.0    292.0  ...     83.0    320.0   
weatherCode_x      116.0    113.0    113.0    113.0  ...    248.0    176.0   
precipMM_x           0.0      0.0      0.0      0.0  ...      0.0      0.0   
visibility_x        10.0     10.0     10.0     10.0  ...      0.0     10.0   
pressure_x        1013.0   1014.0   1014.0   1018.0  ...   1023.0   1022.0   
cloudcover_x        18.0      0.0      1.0      0.0  ...    100.0     93.0   
DewPointF_x         24.0     36.0     10.0     39.0  ...     45.0     47.0   
WindGustKmph_x       5.0     17.0      3.0     18.0  ...      6.0     16.0   
tempF_x             63.0     57.0     40.0     57.0  ...     46.0     50.0   
WindChillF_x        63.0     53.0     39.0     53.0  ...     46.0     46.0   
humidity_x          22.0     48.0     29.0     

In [8]:
y = df['ArrDel15']

In [9]:
y

0          0.0
1          1.0
2          0.0
3          0.0
4          0.0
          ... 
1877189    0.0
1877190    0.0
1877191    0.0
1877192    0.0
1877193    0.0
Name: ArrDel15, Length: 1877194, dtype: float64

In [10]:
y.shape

(1877194,)

In [11]:
x.replace([np.inf, -np.inf], np.nan, inplace=True)
x.fillna(999, inplace=True)

In [12]:
np.any(np.isnan(x))

False

In [13]:
np.all(np.isfinite(x))

True

In [14]:
# Logistic Regression
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 42)

In [15]:
x_train = np.nan_to_num(x_train)

In [16]:
y_train = np.nan_to_num(y_train)

In [17]:
x_test = np.nan_to_num(x_test)

In [18]:
y_test = np.nan_to_num(y_test)

In [19]:
# Logistic Regression
logReg = LogisticRegression()

In [20]:
logReg.fit(x_train,y_train)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [21]:
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [22]:
# Accuracy
score = logReg.score(x_test,y_test)
print(score)

0.7920248029639968


In [23]:
pred = logReg.predict(x_test)

In [24]:
# Confusion matrix
cm = metrics.confusion_matrix(y_test,pred)

In [25]:
cm

array([[296617,    695],
       [ 77387,    740]])

In [26]:
# Classification Report
from sklearn.metrics import classification_report
target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.79      1.00      0.88    297312
     Class 1       0.52      0.01      0.02     78127

    accuracy                           0.79    375439
   macro avg       0.65      0.50      0.45    375439
weighted avg       0.74      0.79      0.70    375439



In [27]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier

decTree = DecisionTreeClassifier()
decTree.fit(x_train, y_train)

DecisionTreeClassifier()

In [28]:
pred1 = decTree.predict(x_test)

In [29]:
cm1 = metrics.confusion_matrix(y_test,pred1)

In [30]:
cm1

array([[243981,  53331],
       [ 48630,  29497]])

In [31]:
score1 = decTree.score(x_test,y_test)
print(score1)

0.728421927396994


In [32]:
# Classification Report
target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred1,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.83      0.82      0.83    297312
     Class 1       0.36      0.38      0.37     78127

    accuracy                           0.73    375439
   macro avg       0.59      0.60      0.60    375439
weighted avg       0.73      0.73      0.73    375439



In [33]:
# Extra Tree Classifier

from sklearn.tree import ExtraTreeClassifier

extTree = ExtraTreeClassifier()
extTree.fit(x_train,y_train)

ExtraTreeClassifier()

In [34]:
pred2 = extTree.predict(x_test)

In [35]:
cm2 = metrics.confusion_matrix(y_test,pred2)

In [36]:
cm2

array([[244243,  53069],
       [ 49815,  28312]])

In [37]:
score2 = extTree.score(x_test,y_test)
print(score2)

0.7259634720953337


In [38]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred2,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.83      0.82      0.83    297312
     Class 1       0.35      0.36      0.35     78127

    accuracy                           0.73    375439
   macro avg       0.59      0.59      0.59    375439
weighted avg       0.73      0.73      0.73    375439



In [39]:
# XG Boost

from xgboost import XGBClassifier


# fit model no training data
xgb = XGBClassifier()
xgb.fit(x_train, y_train)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[13:15:55] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [40]:
pred3 = xgb.predict(x_test)

In [41]:
cm3 = metrics.confusion_matrix(y_test,pred3)

In [42]:
cm3

array([[291886,   5426],
       [ 67703,  10424]])

In [43]:
score3 = xgb.score(x_test,y_test)
print(score3)

0.8052173588785395


In [44]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred3,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.81      0.98      0.89    297312
     Class 1       0.66      0.13      0.22     78127

    accuracy                           0.81    375439
   macro avg       0.73      0.56      0.56    375439
weighted avg       0.78      0.81      0.75    375439



In [45]:
# Random Forest

from sklearn.ensemble import RandomForestClassifier  

ranFor = RandomForestClassifier(n_estimators= 30, criterion="entropy")  
ranFor.fit(x_train,y_train)  

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [46]:
pred4 = ranFor.predict(x_test)

In [47]:
cm4 = metrics.confusion_matrix(y_test,pred4)

In [48]:
cm4

array([[278950,  18362],
       [ 57965,  20162]])

In [49]:
score4 = ranFor.score(x_test,y_test)
print(score4)

0.7966993306502521


In [50]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred4,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.83      0.94      0.88    297312
     Class 1       0.52      0.26      0.35     78127

    accuracy                           0.80    375439
   macro avg       0.68      0.60      0.61    375439
weighted avg       0.76      0.80      0.77    375439

