In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

In [2]:
f = open("/Users/shreyassrinivasan/Desktop/SF_Project/merge_final.csv")
df = pd.read_csv(f)

In [3]:
df = df.dropna()

In [4]:
df.transpose()

0           1           2           3           4        \
Unnamed: 0                0           1           2           3           4   
Unnamed: 0_x            529      243575       33638       64939       63972   
Year                   2016        2016        2016        2016        2016   
Quarter                   4           4           4           4           4   
Month                    12          12          12          12          12   
DayofMonth                1           1           1           1           1   
FlightDate       2016-12-01  2016-12-01  2016-12-01  2016-12-01  2016-12-01   
OriginAirportID       11298       11298       13930       13303       14771   
Origin                  DFW         DFW         ORD         MIA         SFO   
DestAirportID         12892       12892       12892       12892       12892   
Dest                    LAX         LAX         LAX         LAX         LAX   
CRSDepTime             1630        1600        1505        1415        1550   
DepTime                1630        1650        1502        1424        1543   
DepDelayMinutes           0          50           0           9           0   
DepDel15                  0           1           0           0           0   
CRSArrTime             1758        1741        1747        1719        1725   
ArrTime                1748        1832        1738        1716        1710   
ArrDelayMinutes           0          51           0           0           0   
ArrDel15                  0           1           0           0           0   
ArrFlightDate    2016-12-01  2016-12-01  2016-12-01  2016-12-01  2016-12-01   
ArrAbsTime             1700        1700        1700        1700        1700   
DepAbsTime             1600        1600        1500        1400        1500   
Unnamed: 0_y          68800       68800       95151      130286       86367   
windspeedKmph_x          19          19          24          15          10   
winddirDegree_x         169         169         257         140         117   
weatherCode_x           113         113         119         116         113   
precipMM_x                0           0           0         0.8           0   
visibility_x             10          10          10          10          10   
pressure_x             1018        1018        1012        1015        1020   
cloudcover_x              0           0          96          70           0   
DewPointF_x              27          27          34          73          45   
WindGustKmph_x           23          23          31          21          12   
tempF_x                  63          63          42          83          62   
WindChillF_x             61          61          33          81          60   
humidity_x               27          27          77          78          59   
date_x           2016-12-01  2016-12-01  2016-12-01  2016-12-01  2016-12-01   
time_x                 1600        1600        1500        1400        1500   
airport_x               DFW         DFW         ORD         MIA         SFO   
Unnamed: 0.1          24881       24881       24881       24881       24881   
windspeedKmph_y           8           8           8           8           8   
winddirDegree_y         261         261         261         261         261   
weatherCode_y           113         113         113         113         113   
precipMM_y                0           0           0           0           0   
visibility_y             10          10          10          10          10   
pressure_y             1014        1014        1014        1014        1014   
cloudcover_y              0           0           0           0           0   
DewPointF_y              59          59          59          59          59   
WindGustKmph_y           10          10          10          10          10   
tempF_y                  69          69          69          69          69   
WindChillF_y             67          67          67          67       

In [5]:
for i in df.columns:
    print(i)

Unnamed: 0
Unnamed: 0_x
Year
Quarter
Month
DayofMonth
FlightDate
OriginAirportID
Origin
DestAirportID
Dest
CRSDepTime
DepTime
DepDelayMinutes
DepDel15
CRSArrTime
ArrTime
ArrDelayMinutes
ArrDel15
ArrFlightDate
ArrAbsTime
DepAbsTime
Unnamed: 0_y
windspeedKmph_x
winddirDegree_x
weatherCode_x
precipMM_x
visibility_x
pressure_x
cloudcover_x
DewPointF_x
WindGustKmph_x
tempF_x
WindChillF_x
humidity_x
date_x
time_x
airport_x
Unnamed: 0.1
windspeedKmph_y
winddirDegree_y
weatherCode_y
precipMM_y
visibility_y
pressure_y
cloudcover_y
DewPointF_y
WindGustKmph_y
tempF_y
WindChillF_y
humidity_y
date_y
time_y
airport_y


In [8]:
# Columns to be dropped

"""
Unnamed: 0
Unnamed: 0_x
DepDel15
ArrTime
FlightDate
ArrDelayMinutes
ArrDel15
ArrFlightDate
ArrAbsTime
DepAbsTime
Unnamed: 0_y
date_x
time_x
airport_x
Unnamed: 0.1
date_y
time_y
airport_y
OriginAirportID
DestAirportID
DepDelayMinutes
"""

x = df.drop(['Unnamed: 0','Unnamed: 0_x','DepDel15','ArrTime','ArrDelayMinutes','ArrDel15',
            'ArrFlightDate','ArrAbsTime','DepAbsTime','Unnamed: 0_y','date_x','time_x','airport_x','Unnamed: 0.1',
            'date_y','time_y','airport_y','FlightDate','OriginAirportID','DestAirportID','DepDelayMinutes'],axis=1)

In [9]:
x.transpose()

0       1       2       3       4       5       6        \
Year               2016    2016    2016    2016    2016    2016    2016   
Quarter               4       4       4       4       4       4       4   
Month                12      12      12      12      12      12      12   
DayofMonth            1       1       1       1       1       1       1   
Origin              DFW     DFW     ORD     MIA     SFO     DEN     PHX   
Dest                LAX     LAX     LAX     LAX     LAX     LAX     LAX   
CRSDepTime         1630    1600    1505    1415    1550    1625    1725   
DepTime            1630    1650    1502    1424    1543    1624    1733   
CRSArrTime         1758    1741    1747    1719    1725    1755    1745   
windspeedKmph_x      19      19      24      15      10       3       5   
winddirDegree_x     169     169     257     140     117     111     278   
weatherCode_x       113     113     119     116     113     113     116   
precipMM_x            0       0       0     0.8       0       0       0   
visibility_x         10      10      10      10      10      10      10   
pressure_x         1018    1018    1012    1015    1020    1014    1013   
cloudcover_x          0       0      96      70       0       1      18   
DewPointF_x          27      27      34      73      45       9      24   
WindGustKmph_x       23      23      31      21      12       6       5   
tempF_x              63      63      42      83      62      38      63   
WindChillF_x         61      61      33      81      60      35      63   
humidity_x           27      27      77      78      59      32      22   
windspeedKmph_y       8       8       8       8       8       8       8   
winddirDegree_y     261     261     261     261     261     261     261   
weatherCode_y       113     113     113     113     113     113     113   
precipMM_y            0       0       0       0       0       0       0   
visibility_y         10      10      10      10      10      10      10   
pressure_y         1014    1014    1014    1014    1014    1014    1014   
cloudcover_y          0       0       0       0       0       0       0   
DewPointF_y          59      59      59      59      59      59      59   
WindGustKmph_y       10      10      10      10      10      10      10   
tempF_y              69      69      69      69      69      69      69   
WindChillF_y         67      67      67      67      67      67      67   
humidity_y           73      73      73      73      73      73      73   

                7       8       9        ... 1877184 1877185 1877186 1877187  \
Year               2016    2016    2016  ...    2017    2017    2017    2017   
Quarter               4       4       4  ...       1       1       1       1   
Month                12      12      12  ...       2       2       2       2   
DayofMonth            1       1       1  ...      12      11      10       4   
Origin              CLT     DEN     ATL  ...     SFO     SFO     SFO     DFW   
Dest                LAX     LAX     LAX  ...     SEA     SEA     SEA     PHX   
CRSDepTime         1450    1555    1501  ...     550     550     550    2326   
DepTime            1451    1609    1520  ...     556     543     548    2317   
CRSArrTime         1726    1730    1710  ...     755     755     755      55   
windspeedKmph_x      14       1      15  ...       3      13       8      15   
winddirDegree_x     275     132     292  ...      83     320     246     171   
weatherCode_x       113     113     113  ...     248     176     248     122   
precipMM_x            0       0       0  ...       0       0     0.8       0   
visibility_x         10      10      10  ...       0      10       7      10   
pressure_x         1014    1014    1018  ...    1023    1022    1015    1019   
cloudcover_x          0       1       0  ...     100      93     100     100   
DewPointF_x          36      10      39  ...      45      47      51      43   
WindGustKmph_x       17  

In [10]:
flightOrigin = {'DFW':1,'EWR':2,'IAH':3,'JFK':4,'LAS':5,'LAX':6,'MCO':7,'MIA':8,'ORD':9,'PHX':10,'SEA':11,'SFO':12,'ATL':13,'CLT':14,'DEN':15} 

In [11]:
arr1 = [df['Origin'].apply(lambda x: flightOrigin.get(x))]

In [12]:
arr2 = [df['Dest'].apply(lambda x: flightOrigin.get(x))]

In [13]:
x['newOrigin'] = arr1[0]

In [14]:
x['newDest'] = arr2[0]

In [15]:
x.transpose()

0       1       2       3       4       5       6        \
Year               2016    2016    2016    2016    2016    2016    2016   
Quarter               4       4       4       4       4       4       4   
Month                12      12      12      12      12      12      12   
DayofMonth            1       1       1       1       1       1       1   
Origin              DFW     DFW     ORD     MIA     SFO     DEN     PHX   
Dest                LAX     LAX     LAX     LAX     LAX     LAX     LAX   
CRSDepTime         1630    1600    1505    1415    1550    1625    1725   
DepTime            1630    1650    1502    1424    1543    1624    1733   
CRSArrTime         1758    1741    1747    1719    1725    1755    1745   
windspeedKmph_x      19      19      24      15      10       3       5   
winddirDegree_x     169     169     257     140     117     111     278   
weatherCode_x       113     113     119     116     113     113     116   
precipMM_x            0       0       0     0.8       0       0       0   
visibility_x         10      10      10      10      10      10      10   
pressure_x         1018    1018    1012    1015    1020    1014    1013   
cloudcover_x          0       0      96      70       0       1      18   
DewPointF_x          27      27      34      73      45       9      24   
WindGustKmph_x       23      23      31      21      12       6       5   
tempF_x              63      63      42      83      62      38      63   
WindChillF_x         61      61      33      81      60      35      63   
humidity_x           27      27      77      78      59      32      22   
windspeedKmph_y       8       8       8       8       8       8       8   
winddirDegree_y     261     261     261     261     261     261     261   
weatherCode_y       113     113     113     113     113     113     113   
precipMM_y            0       0       0       0       0       0       0   
visibility_y         10      10      10      10      10      10      10   
pressure_y         1014    1014    1014    1014    1014    1014    1014   
cloudcover_y          0       0       0       0       0       0       0   
DewPointF_y          59      59      59      59      59      59      59   
WindGustKmph_y       10      10      10      10      10      10      10   
tempF_y              69      69      69      69      69      69      69   
WindChillF_y         67      67      67      67      67      67      67   
humidity_y           73      73      73      73      73      73      73   
newOrigin             1       1       9       8      12      15      10   
newDest               6       6       6       6       6       6       6   

                7       8       9        ... 1877184 1877185 1877186 1877187  \
Year               2016    2016    2016  ...    2017    2017    2017    2017   
Quarter               4       4       4  ...       1       1       1       1   
Month                12      12      12  ...       2       2       2       2   
DayofMonth            1       1       1  ...      12      11      10       4   
Origin              CLT     DEN     ATL  ...     SFO     SFO     SFO     DFW   
Dest                LAX     LAX     LAX  ...     SEA     SEA     SEA     PHX   
CRSDepTime         1450    1555    1501  ...     550     550     550    2326   
DepTime            1451    1609    1520  ...     556     543     548    2317   
CRSArrTime         1726    1730    1710  ...     755     755     755      55   
windspeedKmph_x      14       1      15  ...       3      13       8      15   
winddirDegree_x     275     132     292  ...      83     320     246     171   
weatherCode_x       113     113     113  ...     248     176     248     122   
precipMM_x            0       0       0  ...       0       0     0.8       0   
visibility_x         10      10      10  ...       0      10       7      10   
pressure_x         1014    1014    1018  ...    1023    1022    1015    1019   
cloudcover_x          0       1    

In [16]:
x = x.drop(['Origin','Dest'],axis=1)

In [17]:
y = df['ArrDel15']

In [18]:
y.shape

(1851334,)

In [19]:
x.shape

(1851334, 33)

In [20]:
np.any(np.isnan(x))

False

In [21]:
np.all(np.isfinite(x))

True

In [25]:
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [ ]:
# No Sampling

In [22]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 40)

In [23]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression()

In [24]:
logReg.fit(x_train,y_train)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [26]:
# Accuracy

score = logReg.score(x_test,y_test)
print(score)

0.8027612506650607


In [27]:
pred = logReg.predict(x_test)

In [28]:
# Confusion matrix

cm = metrics.confusion_matrix(y_test,pred)

In [29]:
cm

array([[292037,    656],
       [ 72375,   5199]])

In [30]:
# Classification Report

from sklearn.metrics import classification_report
target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.80      1.00      0.89    292693
     Class 1       0.89      0.07      0.12     77574

    accuracy                           0.80    370267
   macro avg       0.84      0.53      0.51    370267
weighted avg       0.82      0.80      0.73    370267



In [31]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier

decTree = DecisionTreeClassifier()
decTree.fit(x_train, y_train)

DecisionTreeClassifier()

In [32]:
pred1 = decTree.predict(x_test)

In [33]:
cm1 = metrics.confusion_matrix(y_test,pred1)

In [34]:
cm1

array([[265923,  26770],
       [ 23509,  54065]])

In [35]:
score1 = decTree.score(x_test,y_test)
print(score1)

0.8642088006762687


In [36]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred1,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.91      0.91    292693
     Class 1       0.67      0.70      0.68     77574

    accuracy                           0.86    370267
   macro avg       0.79      0.80      0.80    370267
weighted avg       0.87      0.86      0.87    370267



In [37]:
# Extra Tree Classifier

from sklearn.tree import ExtraTreeClassifier

extTree = ExtraTreeClassifier()
extTree.fit(x_train,y_train)

ExtraTreeClassifier()

In [38]:
pred2 = extTree.predict(x_test)

In [39]:
cm2 = metrics.confusion_matrix(y_test,pred2)

In [40]:
cm2

array([[249130,  43563],
       [ 42275,  35299]])

In [41]:
score2 = extTree.score(x_test,y_test)
print(score2)

0.7681726969997327


In [42]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred2,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.85      0.85      0.85    292693
     Class 1       0.45      0.46      0.45     77574

    accuracy                           0.77    370267
   macro avg       0.65      0.65      0.65    370267
weighted avg       0.77      0.77      0.77    370267



In [43]:
# XG Boost

from xgboost import XGBClassifier


# fit model no training data
xgb = XGBClassifier()
xgb.fit(x_train, y_train)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[20:30:30] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [44]:
pred3 = xgb.predict(x_test)

In [45]:
cm3 = metrics.confusion_matrix(y_test,pred3)

In [46]:
cm3

array([[286970,   5723],
       [ 24539,  53035]])

In [47]:
score3 = xgb.score(x_test,y_test)
print(score3)

0.9182697890981373


In [48]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred3,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.98      0.95    292693
     Class 1       0.90      0.68      0.78     77574

    accuracy                           0.92    370267
   macro avg       0.91      0.83      0.86    370267
weighted avg       0.92      0.92      0.91    370267



In [49]:
# Random Forest

from sklearn.ensemble import RandomForestClassifier  

In [50]:
ranFor = RandomForestClassifier(n_estimators= 30, criterion="entropy")   

In [51]:
ranFor.fit(x_train,y_train) 

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [52]:
pred4 = ranFor.predict(x_test)

In [53]:
cm4 = metrics.confusion_matrix(y_test,pred4)

In [54]:
cm4

array([[286419,   6274],
       [ 42913,  34661]])

In [55]:
score4 = ranFor.score(x_test,y_test)
print(score4)

0.8671580238044438


In [56]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred4,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.87      0.98      0.92    292693
     Class 1       0.85      0.45      0.58     77574

    accuracy                           0.87    370267
   macro avg       0.86      0.71      0.75    370267
weighted avg       0.86      0.87      0.85    370267



In [57]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

In [59]:
import collections

In [ ]:
# Undersampling

In [58]:
rus = RandomUnderSampler(random_state = 42)
x_resampled,y_resampled = rus.fit_resample(x_train,y_train)

In [60]:
collections.Counter(y_resampled)

Counter({0.0: 310465, 1.0: 310465})

In [61]:
# Logistic Regression

logReg.fit(x_resampled,y_resampled)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [62]:
# Accuracy

y_predlogReg = logReg.predict(x_test)
accuracy_score(y_test, y_predlogReg)
score = accuracy_score(y_test,y_predlogReg)
print(score)

0.6098112983333649


In [63]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predlogReg)
print(cm)

[[178397 114296]
 [ 30178  47396]]


In [64]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predlogReg,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.86      0.61      0.71    292693
     Class 1       0.29      0.61      0.40     77574

    accuracy                           0.61    370267
   macro avg       0.57      0.61      0.55    370267
weighted avg       0.74      0.61      0.65    370267



In [65]:
# Decision Tree

decTree.fit(x_resampled,y_resampled)

DecisionTreeClassifier()

In [66]:
# Accuracy

y_preddecTree = decTree.predict(x_test)
accuracy_score(y_test, y_preddecTree)
score = accuracy_score(y_test,y_preddecTree)
print(score)

0.7846716018440747


In [67]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_preddecTree)
print(cm)

[[229010  63683]
 [ 16046  61528]]


In [68]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_preddecTree,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.93      0.78      0.85    292693
     Class 1       0.49      0.79      0.61     77574

    accuracy                           0.78    370267
   macro avg       0.71      0.79      0.73    370267
weighted avg       0.84      0.78      0.80    370267



In [69]:
# Extra Tree Classifier

extTree.fit(x_resampled,y_resampled)

ExtraTreeClassifier()

In [70]:
# Accuracy

y_predextTree = extTree.predict(x_test)
accuracy_score(y_test, y_predextTree)
score = accuracy_score(y_test,y_predextTree)
print(score)

0.6181863358063235


In [71]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predextTree)
print(cm)

[[180521 112172]
 [ 29201  48373]]


In [72]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predextTree,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.86      0.62      0.72    292693
     Class 1       0.30      0.62      0.41     77574

    accuracy                           0.62    370267
   macro avg       0.58      0.62      0.56    370267
weighted avg       0.74      0.62      0.65    370267



In [73]:
# XG Boost

xgb.fit(x_resampled,y_resampled)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[20:48:54] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [74]:
# Accuracy

y_predxgb = xgb.predict(x_test)
accuracy_score(y_test, y_predxgb)
score = accuracy_score(y_test,y_predxgb)
print(score)

0.898635309114774


In [75]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predxgb)
print(cm)

[[271214  21479]
 [ 16053  61521]]


In [76]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predxgb,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.94      0.93      0.94    292693
     Class 1       0.74      0.79      0.77     77574

    accuracy                           0.90    370267
   macro avg       0.84      0.86      0.85    370267
weighted avg       0.90      0.90      0.90    370267



In [77]:
# Random Forest

ranFor.fit(x_resampled,y_resampled)

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [78]:
# Accuracy

y_predranFor = ranFor.predict(x_test)
accuracy_score(y_test, y_predranFor)
score = accuracy_score(y_test,y_predranFor)
print(score)

0.8103908800946344


In [79]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predranFor)
print(cm)

[[241822  50871]
 [ 19335  58239]]


In [80]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predranFor,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.93      0.83      0.87    292693
     Class 1       0.53      0.75      0.62     77574

    accuracy                           0.81    370267
   macro avg       0.73      0.79      0.75    370267
weighted avg       0.84      0.81      0.82    370267



In [ ]:
# Oversampling

In [81]:
ros = RandomOverSampler(random_state = 42)
x_resampled,y_resampled = ros.fit_resample(x_train,y_train)

In [82]:
collections.Counter(y_resampled)

Counter({0.0: 1170602, 1.0: 1170602})

In [83]:
# Logistic Regression

logReg.fit(x_resampled,y_resampled)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [84]:
# Accuracy

y_predlogReg = logReg.predict(x_test)
accuracy_score(y_test, y_predlogReg)
score = accuracy_score(y_test,y_predlogReg)
print(score)

0.6089119473244983


In [85]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predlogReg)
print(cm)

[[178172 114521]
 [ 30286  47288]]


In [86]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predlogReg,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.85      0.61      0.71    292693
     Class 1       0.29      0.61      0.40     77574

    accuracy                           0.61    370267
   macro avg       0.57      0.61      0.55    370267
weighted avg       0.74      0.61      0.64    370267



In [87]:
# Decision Tree

decTree.fit(x_resampled,y_resampled)

DecisionTreeClassifier()

In [88]:
# Accuracy

y_preddecTree = decTree.predict(x_test)
accuracy_score(y_test, y_preddecTree)
score = accuracy_score(y_test,y_preddecTree)
print(score)

0.865532170028655


In [89]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_preddecTree)
print(cm)

[[267312  25381]
 [ 24408  53166]]


In [90]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_preddecTree,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.91      0.91    292693
     Class 1       0.68      0.69      0.68     77574

    accuracy                           0.87    370267
   macro avg       0.80      0.80      0.80    370267
weighted avg       0.87      0.87      0.87    370267



In [91]:
# Extra Tree Classifier

extTree.fit(x_resampled,y_resampled)

ExtraTreeClassifier()

In [92]:
# Accuracy

y_predextTree = extTree.predict(x_test)
accuracy_score(y_test, y_predextTree)
score = accuracy_score(y_test,y_predextTree)
print(score)

0.7557168205646196


In [93]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predextTree)
print(cm)

[[247891  44802]
 [ 45648  31926]]


In [94]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predextTree,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.84      0.85      0.85    292693
     Class 1       0.42      0.41      0.41     77574

    accuracy                           0.76    370267
   macro avg       0.63      0.63      0.63    370267
weighted avg       0.75      0.76      0.76    370267



In [95]:
# XG Boost

xgb.fit(x_resampled,y_resampled)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:01:48] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [96]:
# Accuracy

y_predxgb = xgb.predict(x_test)
accuracy_score(y_test, y_predxgb)
score = accuracy_score(y_test,y_predxgb)
print(score)

0.8992132704237753


In [97]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predxgb)
print(cm)

[[271540  21153]
 [ 16165  61409]]


In [98]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predxgb,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.94      0.93      0.94    292693
     Class 1       0.74      0.79      0.77     77574

    accuracy                           0.90    370267
   macro avg       0.84      0.86      0.85    370267
weighted avg       0.90      0.90      0.90    370267



In [99]:
# Random Forest

ranFor.fit(x_resampled,y_resampled)

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [100]:
# Accuracy

y_predranFor = ranFor.predict(x_test)
accuracy_score(y_test,y_predranFor)
score = accuracy_score(y_test,y_predranFor)
print(score)

0.8636254378597067


In [101]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predranFor)
print(cm)

[[279266  13427]
 [ 37068  40506]]


In [102]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predranFor,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.88      0.95      0.92    292693
     Class 1       0.75      0.52      0.62     77574

    accuracy                           0.86    370267
   macro avg       0.82      0.74      0.77    370267
weighted avg       0.86      0.86      0.85    370267



In [103]:
# Oversampled XG Boost is the best classifier