In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [2]:
f = open("/Users/shreyassrinivasan/Desktop/SF_Project/finalData.csv")
df = pd.read_csv(f)

In [3]:
df.transpose()

0        1        2        3        4        5        \
Unnamed: 0           0.0      1.0      2.0      3.0      4.0      5.0   
Unnamed: 0.1         0.0      1.0      2.0      3.0      4.0      5.0   
Year              2016.0   2016.0   2016.0   2016.0   2016.0   2016.0   
Quarter              4.0      4.0      4.0      4.0      4.0      4.0   
Month               12.0     12.0     12.0     12.0     12.0     12.0   
DayofMonth           1.0      1.0      1.0      1.0      1.0      1.0   
OriginAirportID  11298.0  11298.0  13930.0  13303.0  14771.0  11292.0   
DestAirportID    12892.0  12892.0  12892.0  12892.0  12892.0  12892.0   
DepTime           1630.0   1650.0   1502.0   1424.0   1543.0   1624.0   
DepDelayMinutes      0.0     50.0      0.0      9.0      0.0      0.0   
DepDel15             0.0      1.0      0.0      0.0      0.0      0.0   
CRSArrTime        1758.0   1741.0   1747.0   1719.0   1725.0   1755.0   
ArrTime           1748.0   1832.0   1738.0   1716.0   1710.0   1748.0   
ArrDelayMinutes      0.0     51.0      0.0      0.0      0.0      0.0   
ArrDel15             0.0      1.0      0.0      0.0      0.0      0.0   
windspeedKmph_x     19.0     19.0     24.0     15.0     10.0      3.0   
winddirDegree_x    169.0    169.0    257.0    140.0    117.0    111.0   
weatherCode_x      113.0    113.0    119.0    116.0    113.0    113.0   
precipMM_x           0.0      0.0      0.0      0.8      0.0      0.0   
visibility_x        10.0     10.0     10.0     10.0     10.0     10.0   
pressure_x        1018.0   1018.0   1012.0   1015.0   1020.0   1014.0   
cloudcover_x         0.0      0.0     96.0     70.0      0.0      1.0   
DewPointF_x         27.0     27.0     34.0     73.0     45.0      9.0   
WindGustKmph_x      23.0     23.0     31.0     21.0     12.0      6.0   
tempF_x             63.0     63.0     42.0     83.0     62.0     38.0   
WindChillF_x        61.0     61.0     33.0     81.0     60.0     35.0   
humidity_x          27.0     27.0     77.0     78.0     59.0     32.0   
windspeedKmph_y      8.0      8.0      8.0      8.0      8.0      8.0   
winddirDegree_y    261.0    261.0    261.0    261.0    261.0    261.0   
weatherCode_y      113.0    113.0    113.0    113.0    113.0    113.0   
precipMM_y           0.0      0.0      0.0      0.0      0.0      0.0   
visibility_y        10.0     10.0     10.0     10.0     10.0     10.0   
pressure_y        1014.0   1014.0   1014.0   1014.0   1014.0   1014.0   
cloudcover_y         0.0      0.0      0.0      0.0      0.0      0.0   
DewPointF_y         59.0     59.0     59.0     59.0     59.0     59.0   
WindGustKmph_y      10.0     10.0     10.0     10.0     10.0     10.0   
tempF_y             69.0     69.0     69.0     69.0     69.0     69.0   
WindChillF_y        67.0     67.0     67.0     67.0     67.0     67.0   
humidity_y          73.0     73.0     73.0     73.0     73.0     73.0   
newOrigin            1.0      1.0      9.0      8.0     12.0     15.0   
newDest              6.0      6.0      6.0      6.0      6.0      6.0   
predDelay           10.0      0.0      9.0      3.0     15.0      7.0   

                 6        7        8        9        ...    1851324  \
Unnamed: 0           6.0      7.0      8.0      9.0  ...  1851324.0   
Unnamed: 0.1         6.0      7.0      8.0      9.0  ...  1877184.0   
Year              2016.0   2016.0   2016.0   2016.0  ...     2017.0   
Quarter              4.0      4.0      4.0      4.0  ...        1.0   
Month               12.0     12.0     12.0     12.0  ...        2.0   
DayofMonth           1.0      1.0      1.0      1.0  ...       12.0   
OriginAirportID  14107.0  11057.0  11292.0  10397.0  ...    14771.0   
DestAirportID    12892.0  12892.0  12892.0  12892.0  ...    14747.0   
DepTime           1733.0   1451.0   1609.0   1520.0  ...      556.0   
DepDelayMinutes      8.0      1.0     14.0     19.0  ...        6.0   
DepDel15             0.0      0.0      0.0      1.0  ...        0.0   
CRSArrTime        1745.0 

In [9]:
x = df.copy() 

In [10]:
y = x['ArrDel15']

In [11]:
x = x.drop(['Unnamed: 0','Unnamed: 0.1','ArrDel15','OriginAirportID','DestAirportID','DepDelayMinutes','DepDel15','ArrDelayMinutes','ArrDel15','predDelay','ArrTime'],axis=1)

In [12]:
x.transpose()

0        1        2        3        4        5        \
Year              2016.0   2016.0   2016.0   2016.0   2016.0   2016.0   
Quarter              4.0      4.0      4.0      4.0      4.0      4.0   
Month               12.0     12.0     12.0     12.0     12.0     12.0   
DayofMonth           1.0      1.0      1.0      1.0      1.0      1.0   
DepTime           1630.0   1650.0   1502.0   1424.0   1543.0   1624.0   
CRSArrTime        1758.0   1741.0   1747.0   1719.0   1725.0   1755.0   
windspeedKmph_x     19.0     19.0     24.0     15.0     10.0      3.0   
winddirDegree_x    169.0    169.0    257.0    140.0    117.0    111.0   
weatherCode_x      113.0    113.0    119.0    116.0    113.0    113.0   
precipMM_x           0.0      0.0      0.0      0.8      0.0      0.0   
visibility_x        10.0     10.0     10.0     10.0     10.0     10.0   
pressure_x        1018.0   1018.0   1012.0   1015.0   1020.0   1014.0   
cloudcover_x         0.0      0.0     96.0     70.0      0.0      1.0   
DewPointF_x         27.0     27.0     34.0     73.0     45.0      9.0   
WindGustKmph_x      23.0     23.0     31.0     21.0     12.0      6.0   
tempF_x             63.0     63.0     42.0     83.0     62.0     38.0   
WindChillF_x        61.0     61.0     33.0     81.0     60.0     35.0   
humidity_x          27.0     27.0     77.0     78.0     59.0     32.0   
windspeedKmph_y      8.0      8.0      8.0      8.0      8.0      8.0   
winddirDegree_y    261.0    261.0    261.0    261.0    261.0    261.0   
weatherCode_y      113.0    113.0    113.0    113.0    113.0    113.0   
precipMM_y           0.0      0.0      0.0      0.0      0.0      0.0   
visibility_y        10.0     10.0     10.0     10.0     10.0     10.0   
pressure_y        1014.0   1014.0   1014.0   1014.0   1014.0   1014.0   
cloudcover_y         0.0      0.0      0.0      0.0      0.0      0.0   
DewPointF_y         59.0     59.0     59.0     59.0     59.0     59.0   
WindGustKmph_y      10.0     10.0     10.0     10.0     10.0     10.0   
tempF_y             69.0     69.0     69.0     69.0     69.0     69.0   
WindChillF_y        67.0     67.0     67.0     67.0     67.0     67.0   
humidity_y          73.0     73.0     73.0     73.0     73.0     73.0   
newOrigin            1.0      1.0      9.0      8.0     12.0     15.0   
newDest              6.0      6.0      6.0      6.0      6.0      6.0   

                 6        7        8        9        ...  1851324  1851325  \
Year              2016.0   2016.0   2016.0   2016.0  ...   2017.0   2017.0   
Quarter              4.0      4.0      4.0      4.0  ...      1.0      1.0   
Month               12.0     12.0     12.0     12.0  ...      2.0      2.0   
DayofMonth           1.0      1.0      1.0      1.0  ...     12.0     11.0   
DepTime           1733.0   1451.0   1609.0   1520.0  ...    556.0    543.0   
CRSArrTime        1745.0   1726.0   1730.0   1710.0  ...    755.0    755.0   
windspeedKmph_x      5.0     14.0      1.0     15.0  ...      3.0     13.0   
winddirDegree_x    278.0    275.0    132.0    292.0  ...     83.0    320.0   
weatherCode_x      116.0    113.0    113.0    113.0  ...    248.0    176.0   
precipMM_x           0.0      0.0      0.0      0.0  ...      0.0      0.0   
visibility_x        10.0     10.0     10.0     10.0  ...      0.0     10.0   
pressure_x        1013.0   1014.0   1014.0   1018.0  ...   1023.0   1022.0   
cloudcover_x        18.0      0.0      1.0      0.0  ...    100.0     93.0   
DewPointF_x         24.0     36.0     10.0     39.0  ...     45.0     47.0   
WindGustKmph_x       5.0     17.0      3.0     18.0  ...      6.0     16.0   
tempF_x             63.0     57.0     40.0     57.0  ...     46.0     50.0   
WindChillF_x        63.0     53.0     39.0     53.0  ...     46.0     46.0   
humidity_x          22.0     48.0     29.0     54.0  ...     98.0     92.0   
windspeedKmph_y      8.0      8.0      8.0      8.0  ...      4.0     10.0   
winddirDegree_y    261.0    261.0    261.0    2

In [ ]:
# No Sampling

In [13]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 40)

In [14]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression()

In [15]:
logReg.fit(x_train,y_train)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [16]:
# Accuracy

score = logReg.score(x_test,y_test)
print(score)

0.7923039320274289


In [17]:
pred = logReg.predict(x_test)

In [18]:
# Confusion matrix

cm = metrics.confusion_matrix(y_test,pred)

In [19]:
cm

array([[291691,   1002],
       [ 75901,   1673]])

In [20]:
# Classification Report

from sklearn.metrics import classification_report
target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.79      1.00      0.88    292693
     Class 1       0.63      0.02      0.04     77574

    accuracy                           0.79    370267
   macro avg       0.71      0.51      0.46    370267
weighted avg       0.76      0.79      0.71    370267



In [21]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier

decTree = DecisionTreeClassifier()
decTree.fit(x_train, y_train)

DecisionTreeClassifier()

In [22]:
pred1 = decTree.predict(x_test)

In [23]:
cm1 = metrics.confusion_matrix(y_test,pred1)

In [24]:
cm1

array([[255366,  37327],
       [ 34530,  43044]])

In [25]:
score1 = decTree.score(x_test,y_test)
print(score1)

0.8059319356032268


In [26]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred1,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.88      0.87      0.88    292693
     Class 1       0.54      0.55      0.55     77574

    accuracy                           0.81    370267
   macro avg       0.71      0.71      0.71    370267
weighted avg       0.81      0.81      0.81    370267



In [27]:
# Extra Tree Classifier

from sklearn.tree import ExtraTreeClassifier

extTree = ExtraTreeClassifier()
extTree.fit(x_train,y_train)

ExtraTreeClassifier()

In [28]:
pred2 = extTree.predict(x_test)

In [29]:
cm2 = metrics.confusion_matrix(y_test,pred2)

In [30]:
cm2

array([[246337,  46356],
       [ 45543,  32031]])

In [31]:
score2 = extTree.score(x_test,y_test)
print(score2)

0.7518034283368488


In [32]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred2,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.84      0.84      0.84    292693
     Class 1       0.41      0.41      0.41     77574

    accuracy                           0.75    370267
   macro avg       0.63      0.63      0.63    370267
weighted avg       0.75      0.75      0.75    370267



In [33]:
# XG Boost

from xgboost import XGBClassifier


# fit model no training data
xgb = XGBClassifier()
xgb.fit(x_train, y_train)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[18:27:19] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [34]:
pred3 = xgb.predict(x_test)

In [35]:
cm3 = metrics.confusion_matrix(y_test,pred3)

In [36]:
cm3

array([[289338,   3355],
       [ 45536,  32038]])

In [37]:
score3 = xgb.score(x_test,y_test)
print(score3)

0.8679574469234363


In [38]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred3,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.86      0.99      0.92    292693
     Class 1       0.91      0.41      0.57     77574

    accuracy                           0.87    370267
   macro avg       0.88      0.70      0.74    370267
weighted avg       0.87      0.87      0.85    370267



In [39]:
# Random Forest

from sklearn.ensemble import RandomForestClassifier 

In [40]:
ranFor = RandomForestClassifier(n_estimators= 30, criterion="entropy")   

In [41]:
ranFor.fit(x_train,y_train) 

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [42]:
pred4 = ranFor.predict(x_test)

In [43]:
cm4 = metrics.confusion_matrix(y_test,pred4)

In [44]:
cm4

array([[282046,  10647],
       [ 51164,  26410]])

In [45]:
score4 = ranFor.score(x_test,y_test)
print(score4)

0.8330637080809253


In [46]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,pred4,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.85      0.96      0.90    292693
     Class 1       0.71      0.34      0.46     77574

    accuracy                           0.83    370267
   macro avg       0.78      0.65      0.68    370267
weighted avg       0.82      0.83      0.81    370267



In [47]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

In [ ]:
# Undersampling

In [48]:
rus = RandomUnderSampler(random_state = 42)
x_resampled,y_resampled = rus.fit_resample(x_train,y_train)

In [49]:
import collections
collections.Counter(y_resampled)

Counter({0.0: 310465, 1.0: 310465})

In [50]:
# Logistic Regression

logReg.fit(x_resampled,y_resampled)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [51]:
# Accuracy

y_predlogReg = logReg.predict(x_test)
accuracy_score(y_test, y_predlogReg)
score = accuracy_score(y_test,y_predlogReg)
print(score)

0.6058519932913277


In [52]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predlogReg)
print(cm)

[[177197 115496]
 [ 30444  47130]]


In [53]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predlogReg,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.85      0.61      0.71    292693
     Class 1       0.29      0.61      0.39     77574

    accuracy                           0.61    370267
   macro avg       0.57      0.61      0.55    370267
weighted avg       0.74      0.61      0.64    370267



In [54]:
# Decision Tree

decTree.fit(x_resampled,y_resampled)

DecisionTreeClassifier()

In [55]:
# Accuracy

y_preddecTree = decTree.predict(x_test)
accuracy_score(y_test, y_preddecTree)
score = accuracy_score(y_test,y_preddecTree)
print(score)

0.695914029605663


In [56]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_preddecTree)
print(cm)

[[203322  89371]
 [ 23222  54352]]


In [57]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_preddecTree,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.90      0.69      0.78    292693
     Class 1       0.38      0.70      0.49     77574

    accuracy                           0.70    370267
   macro avg       0.64      0.70      0.64    370267
weighted avg       0.79      0.70      0.72    370267



In [58]:
# Extra Tree Classifier

extTree.fit(x_resampled,y_resampled)

ExtraTreeClassifier()

In [59]:
# Accuracy

y_predextTree = extTree.predict(x_test)
accuracy_score(y_test, y_predextTree)
score = accuracy_score(y_test,y_predextTree)
print(score)

0.6144836023734225


In [60]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predextTree)
print(cm)

[[179812 112881]
 [ 29863  47711]]


In [61]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predextTree,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.86      0.61      0.72    292693
     Class 1       0.30      0.62      0.40     77574

    accuracy                           0.61    370267
   macro avg       0.58      0.61      0.56    370267
weighted avg       0.74      0.61      0.65    370267



In [62]:
# XG Boost

xgb.fit(x_resampled,y_resampled)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[18:38:49] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [63]:
# Accuracy

y_predxgb = xgb.predict(x_test)
accuracy_score(y_test, y_predxgb)
score = accuracy_score(y_test,y_predxgb)
print(score)

0.8172696999732625


In [64]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predxgb)
print(cm)

[[246973  45720]
 [ 21939  55635]]


In [65]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predxgb,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.84      0.88    292693
     Class 1       0.55      0.72      0.62     77574

    accuracy                           0.82    370267
   macro avg       0.73      0.78      0.75    370267
weighted avg       0.84      0.82      0.83    370267



In [66]:
# Random Forest

ranFor.fit(x_resampled,y_resampled)

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [67]:
# Accuracy

y_predranFor = ranFor.predict(x_test)
accuracy_score(y_test, y_predranFor)
score = accuracy_score(y_test,y_predranFor)
print(score)

0.747179737864838


In [68]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predranFor)
print(cm)

[[223799  68894]
 [ 24717  52857]]


In [69]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predranFor,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.90      0.76      0.83    292693
     Class 1       0.43      0.68      0.53     77574

    accuracy                           0.75    370267
   macro avg       0.67      0.72      0.68    370267
weighted avg       0.80      0.75      0.76    370267



In [ ]:
# Oversampling

In [70]:
ros = RandomOverSampler(random_state = 42)
x_resampled,y_resampled = ros.fit_resample(x_train,y_train)

In [71]:
import collections
collections.Counter(y_resampled)

Counter({0.0: 1170602, 1.0: 1170602})

In [72]:
# Logistic Regression

logReg.fit(x_resampled,y_resampled)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [73]:
# Accuracy

y_predlogReg = logReg.predict(x_test)
accuracy_score(y_test, y_predlogReg)
score = accuracy_score(y_test,y_predlogReg)
print(score)

0.6074481387755323


In [74]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predlogReg)
print(cm)

[[178137 114556]
 [ 30793  46781]]


In [75]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predlogReg,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.85      0.61      0.71    292693
     Class 1       0.29      0.60      0.39     77574

    accuracy                           0.61    370267
   macro avg       0.57      0.61      0.55    370267
weighted avg       0.73      0.61      0.64    370267



In [76]:
# Decision Tree

decTree.fit(x_resampled,y_resampled)

DecisionTreeClassifier()

In [77]:
# Accuracy

y_preddecTree = decTree.predict(x_test)
accuracy_score(y_test, y_preddecTree)
score = accuracy_score(y_test,y_preddecTree)
print(score)

0.8078494707872967


In [78]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_preddecTree)
print(cm)

[[257680  35013]
 [ 36134  41440]]


In [79]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predlogReg,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.85      0.61      0.71    292693
     Class 1       0.29      0.60      0.39     77574

    accuracy                           0.61    370267
   macro avg       0.57      0.61      0.55    370267
weighted avg       0.73      0.61      0.64    370267



In [80]:
# Extra Tree Classifier

extTree.fit(x_resampled,y_resampled)

ExtraTreeClassifier()

In [81]:
# Accuracy

y_predextTree = extTree.predict(x_test)
accuracy_score(y_test, y_predextTree)
score = accuracy_score(y_test,y_predextTree)
print(score)

0.7477279908822553


In [82]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predextTree)
print(cm)

[[246806  45887]
 [ 47521  30053]]


In [83]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predextTree,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.84      0.84      0.84    292693
     Class 1       0.40      0.39      0.39     77574

    accuracy                           0.75    370267
   macro avg       0.62      0.62      0.62    370267
weighted avg       0.75      0.75      0.75    370267



In [84]:
# XG Boost

xgb.fit(x_resampled,y_resampled)

/Users/shreyassrinivasan/miniconda3/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[18:48:33] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [85]:
# Accuracy

y_predxgb = xgb.predict(x_test)
accuracy_score(y_test, y_predxgb)
score = accuracy_score(y_test,y_predxgb)
print(score)

0.8204808962181345


In [86]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predxgb)
print(cm)

[[248209  44484]
 [ 21986  55588]]


In [87]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predxgb,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.92      0.85      0.88    292693
     Class 1       0.56      0.72      0.63     77574

    accuracy                           0.82    370267
   macro avg       0.74      0.78      0.75    370267
weighted avg       0.84      0.82      0.83    370267



In [88]:
# Random Forest

ranFor.fit(x_resampled,y_resampled)

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [89]:
# Accuracy

y_predranFor = ranFor.predict(x_test)
accuracy_score(y_test,y_predranFor)
score = accuracy_score(y_test,y_predranFor)
print(score)

0.8258689000099928


In [90]:
# Confusion Matrix

cm = metrics.confusion_matrix(y_test,y_predranFor)
print(cm)

[[272709  19984]
 [ 44491  33083]]


In [91]:
# Classification Report

target_names=["Class 0","Class 1"]
print(classification_report(y_test,y_predranFor,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.86      0.93      0.89    292693
     Class 1       0.62      0.43      0.51     77574

    accuracy                           0.83    370267
   macro avg       0.74      0.68      0.70    370267
weighted avg       0.81      0.83      0.81    370267

